version: '3.8'
services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - redis
    volumes:
      - ./data:/app/data
  worker:
    build: .
    container_name: celery_worker
    command: celery -A tasks worker --loglevel=info
    depends_on:
      - redis
  beat:
    build: .
    container_name: celery_beat
    command: celery -A tasks beat --loglevel=info
    depends_on:
      - redis
      - worker